name: Simple Build Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Show Project Structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== LevelMap Directory ==="
        ls -la LevelMap/ || echo "LevelMap directory not found"
    
    - name: List Available Schemes
      run: |
        echo "=== Available Schemes ==="
        xcodebuild -list -project LevelMap.xcodeproj
    
    - name: Build for iOS Simulator
      run: |
        echo "=== Building for iOS Simulator ==="
        xcodebuild -project LevelMap.xcodeproj \
          -scheme LevelMap \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          build
    
    - name: Build Success
      run: |
        echo "🎉 BUILD SUCCESSFUL! 🎉"
        echo "Your LevelMap app compiles correctly!"
        echo ""
        echo "Next: We can work on TestFlight deployment once this basic build works."
