name: Build Device IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Build for Device
      run: |
        echo "=== Building for iOS Device ==="
        xcodebuild -project LevelMap.xcodeproj \
          -scheme LevelMap \
          -configuration Debug \
          -destination 'generic/platform=iOS' \
          -allowProvisioningUpdates \
          -archivePath ./build/LevelMap.xcarchive \
          archive
    
    - name: Export Development IPA
      run: |
        echo "=== Creating Development IPA ==="
        # Create development export options
        cat > devExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>3GJF2X7ANU</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>manageAppVersionAndBuildNumber</key>
            <false/>
            <key>destination</key>
            <string>export</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
        </dict>
        </plist>
        EOF
        
        xcodebuild -exportArchive \
          -archivePath ./build/LevelMap.xcarchive \
          -exportPath ./build/device-ipa \
          -exportOptionsPlist devExportOptions.plist
    
    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LevelMap-Device-IPA
        path: ./build/device-ipa/LevelMap.ipa
        retention-days: 30
    
    - name: Success Message
      run: |
        echo "🎉 DEVICE IPA BUILD SUCCESSFUL! 🎉"
        echo ""
        echo "Next steps for manual installation:"
        echo "1. Go to GitHub Actions tab"
        echo "2. Click on this workflow run"
        echo "3. Scroll down to 'Artifacts'"
        echo "4. Download 'LevelMap-Device-IPA'"
        echo "5. Install using one of these methods:"
        echo ""
        echo "Method 1 - AltStore (Recommended):"
        echo "- Install AltStore on your device"
        echo "- Drag the .ipa file to AltStore"
        echo "- Install LevelMap from AltStore"
        echo ""
        echo "Method 2 - Xcode (if you have Mac access):"
        echo "- Open Xcode on Mac"
        echo "- Window > Devices and Simulators"
        echo "- Drag .ipa to your device"
        echo ""
        echo "Method 3 - 3uTools (Windows):"
        echo "- Install 3uTools on Windows"
        echo "- Connect your device"
        echo "- Install the .ipa file"

