name: iOS Build and TestFlight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    
    - name: List Available Schemes
      run: |
        xcodebuild -list -project LevelMap.xcodeproj
    
    - name: Build and Archive
      run: |
        xcodebuild -project LevelMap.xcodeproj \
          -scheme LevelMap \
          -configuration Release \
          -archivePath ./build/LevelMap.xcarchive \
          -destination 'generic/platform=iOS' \
          archive
          
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath ./build/LevelMap.xcarchive \
          -exportPath ./build/ipa \
          -exportOptionsPlist exportOptions.plist
          
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight@v1
      with:
        app-path: ./build/ipa/LevelMap.ipa
        api-key: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
        api-key-id: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        api-issuer-id: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
